### ISSUE TITLE
elasticsearch 5

### ISSUE THREAD

**Issue by gadieichhorn** [sczyh30/vertx-blueprint-microservice#12]
the new version of ES doesnt work with docker OOtB so you need to do few changes to the process.

first, after you create a docker host (docker-machine) you need to ssh into the host and update the map
I called my machine "vertx"

>> docker-machine ssh vertx
Boot2Docker version 1.12.3, build HEAD : 7fc7575 - Thu Oct 27 17:23:17 UTC 201
Docker version 1.12.3, build 6b644ec
docker@vertx:~$ **sudo sysctl -w vm.max_map_count=262144**
vm.max_map_count = 262144

you also need to make some changes to the docker-compose.yml

```
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    command:
      - "-E"
      - "network.host=0.0.0.0"
      - "-E"
      - "discovery.zen.minimum_master_nodes=1"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g -Des.path.conf=/etc/elasticsearch"

```

here is a working ELK stack I used as reference.
https://github.com/deviantony/docker-elk
